# Generated by Django 4.1.4 on 2022-12-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expired_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Penalty_fee_amount', models.FloatField(default=0.0)),
                ('Payment_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='version2.payment_user')),
            ],
        ),
    ]
